### PR TITLE
Support getting all objects from bucket

### PR DESCRIPTION
**Pull request by guy-br**

### CODE REVIEW

**Comment by burdandrei** [comment]
:+1:

**Comment by pottava** [comment]
@guy-br I think it does not return all objects in the bucket if you specify `Delimiter: /` in `s3.ListObjectsInput`. So you might have to define `s3.ListObjectsInput` separately in the `getObjsFromS3` function.

Cloud you add `GET_ALL_OBJ_IN_BUCKET` option in README.md as well?

**Comment by guy-br** [comment]
@pottava what i meant was adding an env_var to get all pages in a directory and that is why i left the Delimiter. ill make changes to support both options and of course add GET_ALL_OBJ_IN_BUCKET to README.md as well. tnx for your work.

**Comment by pottava** [comment]
@guy-br I got it, it seems awesome. Thanks for your great idea and implementing features.

**Comment by guy-br** [comment]
@pottava i have updated the name of the var from "GET_ALL_OBJ_IN_BUCKET" to "GET_ALL_PAGES_IN_DIR" for better understanding the meaning. also updated README.
thank you again.

**Comment by pottava** [comment]
@guy-br I've reviewed the commit. Looks great. So thank you for your awesome work, again!

**Pull request merged**
